site_name: IDESA

extra_css:
  - _assets/main.css
extra_javascript:
  - _assets/scg.min.js
  - _assets/main.js

nav:
  - Home: index.md
  - Build:
    - Build on Linux: build/linux-build.md
  - Development:
    - Git-workflow: dev/git-workflow.md
    - Pull requests: dev/pr.md
    - Codestyle: dev/codestyle.md
    - Project structure: dev/project_structure.md
  - IDESA agents:
    - Message reply agent: agents/messageReplyAgent.md
    - Non-atomic action interpretation agent: agents/nonAtomicActionInterpretationAgent.md
    - Speech to text agent: agents/speechToTextAgent.md
    - Message topic classification agent: agents/messageTopicClassificationAgent.md
    - Standard message reply agent: agents/standardMessageReplyAgent.md
    - Text to speech agent: agents/textToSpeechAgent.md
    - Error message reply agent: agents/errorMessageReplyAgent.md
  - License: license.md
  - Changelog: changelog.md
  - Thirdparty: thirdparty.md

theme: material

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
